name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          registry: dockerhub.qingcloud.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and Push to Private Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: dockerhub.qingcloud.com/iprometheus/redeploy:${{ github.run_number }}
